### ISSUE TITLE
Improve airy config apply

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1150]
**Current state**

`airy config apply` covers creating config map artifacts for `facebook`, `twilio`, `google`, and `webhook`. 

**Desired state**

`airy config apply` is capable of creating all necessary config maps without the need to write any additional go code to cover new structures.

**Proposal**
@lucapette had the idea to say as a convention that every leaf block in the `airy.yaml` gets turned into a config map by default. This way the code becomes simple while the output stays predictable. 

I.e.
```yaml
apps:
  sources:
    facebook:
        appId: "123"
```
becomes a configmap "apps-sources-facebook" with content:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "apps-sources-facebook"
  namespace: default
data:
  appId: "123"
```
