### ISSUE TITLE
Media Resolver crashes on bad configuration

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1497]
### Current Behaviour
On startup, the media resolver app tries to build an AWS client based on the config values and that fails if they are invalid which results in the app crashing

### Expected Behaviour
The app should log that the configuration is invalid and not crash

### Example configuration which produced the error
```yaml
media-resolver:
    storage:
      s3:
        key: "changeme"
        secret: "changeme"
        bucket: "changeme"
        region: "changeme"
        path: "path"
```
