### ISSUE TITLE
Update the docs sources in airy.yaml

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1635]
With the recent change of how we apply the configuration, we need to update the docs to reflect what is currently required to be set in the `airy.yaml` file, for the sources components.

This should be the eventual configuration, for starting all of the sources.
```
components:
  sources:
    facebook:
      appId:
      appSecret:
      webhookSecret:
    twilio:
      authToken:
      accountSid:
    google:
      saFile:
      partnerKey:
```
