### ISSUE TITLE
Add Google Workspace Auth Provider in Security

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2615]
## This is how we could improve the [documentation](https://docs.airy.co):

As Google Login is accessible to everybody with a Google account and Google Workspace extremely popular as a SSO provider in the enterprise, we should add a guide how to authenticate an Airy instance with Google; I would recommend as the no 1 option above Github.

1. We should give an example for the relevant `airy.yaml` section

2. We should write a step by step guide (in the docs or as a tutorial on the blog linked from the docs) 

### The following conditions should have been done before:

- HTTPS should have been properly set up and configured for the relevant Airy instance

### The security security section of the `airy.yaml` file should look as follows: 

```
security:
  allowedOrigins: "*" # Authorized Domains for CORS, e.g. public ("*") or "mydomain.com"
  systemToken: "my-system-token-for-the-API"
  jwtSecret: "a-long-string-with-a-minimum-length-of-256-bits"
  oidc:
    allowedEmailPatterns: "*@mydomain.com" # comma separated email patterns, e.g. everyone with an email for a URL
    provider: "google"
    clientId: "A-CLIENT-ID-GENERATED-BY-GOOGLE"
    clientSecret: "A-CLIENT-SECRET-GENERATED-BY-GOOGLE"
    logoutSuccessUrl: "https://airy.mydomain.com" # URL to redirect to when logged out
    scope: "openid,profile,email" 
    clientAuthenticationMethod: "basic" 
    authorizationGrantType: "authorization_code"
    authorizationUri: "https://accounts.google.com/o/oauth2/auth"
    tokenUri: "https://oauth2.googleapis.com/token"
    userInfoUri: "https://openidconnect.googleapis.com/v1/userinfo"
    userInfoAuthenticationMethod: "form" 
    userNameAttributeName: "email" 
    issuerUri: "https://accounts.google.com"
    jwkSetUri: "https://www.googleapis.com/oauth2/v3/certs"
```

After saving the `airy.yaml` file, the configuration needs to be applied, e.g. with the CLI run `airy config apply` (we should support applying the configuration with `helm upgrade CHART -file airy.yaml` as well. 

## Steps to create a Google Client ID and Client secret:

1. Create a free Google Cloud project at https://cloud.google.com or use an existing GCP project

2. In"APIs & Services" select the "Credentials" section and  create a new "OAuth Client ID"

![Screenshot 2021-11-24 at 17 42 26](https://user-images.githubusercontent.com/9045481/143283403-7458abcd-4920-4b5a-a8e7-620eed56027d.png)

3. Creating an OAuth Client ID 

- Select "Web Application"
- choose a name e.g. "Airy Core" 
- add the Authorized Origin URI where your Airy instance is running e.g. "https://airy.mydomain.com"
- add the Authorized Redirect URI ending with "/login/oauth2/code/google", e.g. "https://airy.mydomain.com/login/oauth2/code/google"
- click "Save" and copy the generated Client ID and Client Secret to your `airy.yaml` file
- don't forget that you need to apply the configuration (link)

![Screenshot 2021-11-24 at 17 42 48](https://user-images.githubusercontent.com/9045481/143283456-36dda5b3-66c9-4688-9b69-ae899b77c383.png)

4. Configure the OAuth consent screen

In case you have created a new GCP project or not configured the OAuth consent screen before, you need to select the "OAuth consent screen section" in "APIs & Services".

- Select the App to be "Internal" in case you want to configure Google Workspace for your organization (only select "External" in case you need people with email addresses outside of your organization in which case an additional review process might be required)
- choose a name, e.g. "Airy Core" which will be displayed to users on your login screen
- optional: upload an image, e.g. your company logo
- your Authorized Origin URI and Authorized Redirect URI should have been added under the Authorized Domains section, otherwise please add them and other Authorized domains you might require
- give a developer contact email address

![Screenshot 2021-11-24 at 17 43 23](https://user-images.githubusercontent.com/9045481/143285328-78bfe4e6-f03d-49d1-8aff-8185a2b11928.png)

- On the next page just add the relevant non-sensitive scopes: `openid`, `profile` and `email`

![Screenshot 2021-11-24 at 18 25 44](https://user-images.githubusercontent.com/9045481/143286721-eb79ce90-5853-404b-af88-bc003b410816.png)
