### ISSUE TITLE
Fix inline IBM Watson Assistant Configmap data and Deployment configuration

### ISSUE THREAD

**Issue by bilge-cakmak** [airyhq/airy#3910]
backend/components/ibm-watson-assistant/helm/templates/configmap.yaml 
uses data configuration naming convention is like below
```
data:
  ibmWatsonAssistantApiKey
  ibmWatsonAssistantAssistantId
  ibmWatsonAssistantURL
```
backend/components/ibm-watson-assistant/helm/templates/deployment.yaml has a key naming connvention is different 
```
          env:
            - name: IBMWATSONASSISTANT_URL
              valueFrom:
                configMapKeyRef:
                  key: ibm-watson-assistant.URL
                  name: {{ .Values.component }}
            - name: IBMWATSONASSISTANT_APIKEY
              valueFrom:
                configMapKeyRef:
                  key: ibm-watson-assistant.apiKey
                  name: {{ .Values.component }}
            - name: IBMWATSONASSISTANT_ASSISTANTID
              valueFrom:
                configMapKeyRef:
                  key: ibm-watson-assistant.assistantId
                  name: {{ .Values.component }}
```
