### ISSUE TITLE
Kubernetes controller for updating configuration

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#450]
We need to create a kubernetes controller, called `airy-controller` which we will use to update the pods, when we change the configuration from the `cli` client. The client will update the appropriate configMaps, which should be annotated with the type of the `Airy apps` which are affected, for example

```
kind: ConfigMap
metadata:
  name: kafka-config
  annotations:
    airy.co/app-type: '[{"WEBHOOKS": "webhooks"}, {"SOURCES":"sources"}]'
...
kind: ConfigMap
metadata:
  name: postgres-conig
  annotations:
    airy.co/app-type: '[{"API-AUTH": "api-auth"}]'
```

Then the controller would need to pickup a change of a particular configMap and restart the proper pods, so that the configuration is applied.

The controller would also need to expose a `health` endpoint, so that the `cli` can check if the controller is running and healthy.
