### ISSUE TITLE
Remove airy label from services

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#506]
There are labels with the key `airy` which are configured for the services, but are not used.
Example:
```
apiVersion: v1
kind: Service
metadata:
  name: sources-facebook-webhook
  namespace: default
  labels:
    airy: sources.webhook
```

We should remove them or change them to `type` as it is for the deployments.
